# Generated by Django 5.0.4 on 2025-08-04 04:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('full_name', models.CharField(max_length=150)),
                ('school_2024_2025', models.CharField(max_length=150)),
                ('class_2024_2025', models.CharField(max_length=150)),
                ('school_2025_2026', models.CharField(max_length=150)),
                ('class_2025_2026', models.CharField(max_length=150)),
                ('essay_text', models.TextField(blank=True, null=True)),
                ('essay_upload', models.FileField(blank=True, upload_to='essays/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])])),
                ('report_card', models.FileField(upload_to='report_cards/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])])),
                ('id_photo', models.ImageField(upload_to='id_photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Shortlisted', 'Shortlisted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('year', 'email')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recommendation_letters/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='applications.applicant')),
            ],
            options={
                'verbose_name': 'Recommendation Letter',
                'verbose_name_plural': 'Recommendation Letters',
            },
        ),
    ]
